# Generated by Django 3.2.7 on 2022-01-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sharing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharing',
            old_name='owner',
            new_name='user',
        ),
    ]
