# Generated by Django 3.2.7 on 2022-02-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_owner_sharing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='target',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
