# Generated by Django 3.2.7 on 2022-02-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_share_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='target2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
