# Generated by Django 3.2.7 on 2022-02-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_share_target2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharing',
            old_name='task_name',
            new_name='task',
        ),
    ]
