# Generated by Django 3.2.7 on 2022-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_task_name_sharing_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='view_only',
            field=models.BooleanField(default=False),
        ),
    ]
